kind: Service
apiVersion: v1
metadata:
  name: factory-control
  labels:
    app: factory-control
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: factory-control
